spring:
  application:
    name: rest-with-spring-boot-and-java-saccucci
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_saccucci?useTimezone=true&serverTimezone=UTC
    username: root
    password: # colocar a senha do root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false

logging:
  level: # TRACE, DEBUG, INFO, WARN, ERROR # INFO = configuração default/padrão // WARN = mais recomendado em ambientes de produção
    # root: WARN # root: <level> = Definição do level de LOGs para toda a aplicação
    br.com.saccucci: DEBUG # root: <level> = Definição do level de LOGs para um package/pacote específico